[build]
  functions = "netlify/functions"
  publish = "dist"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5000
  port = 8888
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true